global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-tomcat'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-tomcat:8080']

  - job_name: 'spring-netty'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-netty:8080']

  - job_name: 'node-express'
    static_configs:
      - targets: ['node-express:3000']

  - job_name: 'node-fastify'
    static_configs:
      - targets: ['node-fastify:3000']

  - job_name: 'go-nethttp'
    static_configs:
      - targets: ['go-nethttp:8080']

  - job_name: 'go-fiber'
    static_configs:
      - targets: ['go-fiber:8080']

  - job_name: 'python-flask'
    static_configs:
      - targets: ['python-flask:5000']

  - job_name: 'python-fastapi'
    static_configs:
      - targets: ['python-fastapi:8000']

  - job_name: 'rust-actix'
    static_configs:
      - targets: ['rust-actix:8080']

  - job_name: 'rust-axum'
    static_configs:
      - targets: ['rust-axum:8080']

  - job_name: 'cpp-pistache'
    static_configs:
      - targets: ['cpp-pistache:8080']

  - job_name: 'csharp-aspnet'
    static_configs:
      - targets: ['csharp-aspnet:8080'] 